name: Create Daily Standup Discussions

on:
  schedule:
    - cron:  '*/2 * * * *' # Runs M-F at 12:01am UTC

jobs:
  create_discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MLH-Fellowship/create-standup-discussions@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORGANIZATION_TOKEN }}
        with:
          organization: "Private"
          team_slugs: "team-1, team-2"